// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Emotion classification result from EfficientNet.
class EmotionResult {
  final String label;
  final double confidence;

  const EmotionResult({required this.label, required this.confidence});

  @override
  int get hashCode => label.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmotionResult &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          confidence == other.confidence;
}
