// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'features/detection/detection_types.dart';
import 'features/emotion/emotion_types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'shared/types/bbox.dart';

/// Initialises all ONNX sessions from the given model directory.
/// Must be called once before any inference function.
Future<void> initModels({required String modelDir}) =>
    RustLib.instance.api.crateApiInitModels(modelDir: modelDir);

/// Computes a 512-dim CLIP image embedding from raw RGB24 pixels.
Future<Float32List> embedImage({
  required List<int> pixels,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiEmbedImage(
  pixels: pixels,
  width: width,
  height: height,
);

/// Runs YOLOv8-nano object detection on raw RGB24 pixels.
Future<List<Detection>> detectObjects({
  required List<int> pixels,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiDetectObjects(
  pixels: pixels,
  width: width,
  height: height,
);

/// Computes a 128-dim MobileFaceNet face embedding using the given bounding box.
Future<Float32List> embedFace({
  required List<int> pixels,
  required int width,
  required int height,
  required BBox bbox,
}) => RustLib.instance.api.crateApiEmbedFace(
  pixels: pixels,
  width: width,
  height: height,
  bbox: bbox,
);

/// Classifies the emotion in the face region described by bbox.
Future<EmotionResult> classifyEmotion({
  required List<int> pixels,
  required int width,
  required int height,
  required BBox bbox,
}) => RustLib.instance.api.crateApiClassifyEmotion(
  pixels: pixels,
  width: width,
  height: height,
  bbox: bbox,
);

/// Computes a 64-bit perceptual hash for the given pixels, returned as a 16-char hex string.
Future<String> computePhash({
  required List<int> pixels,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiComputePhash(
  pixels: pixels,
  width: width,
  height: height,
);

/// Computes a 512-dim CLIP text embedding for the given query string.
Future<Float32List> embedText({required String query}) =>
    RustLib.instance.api.crateApiEmbedText(query: query);
